import Head from 'next/head'
import { Flex, Box, Heading } from '@chakra-ui/react'
import LotomaniaImage from '../../assets/images/loterias/lotomania.png'
import DuplasenaImage from '../../assets/images/loterias/dupla-sena.png'
import LotofacilImage from '../../assets/images/loterias/lotofacil.png'
import MegasenaImage from '../../assets/images/loterias/megasena.png'
import QuinaImage from '../../assets/images/loterias/quina.png'
import TimemaniaImage from '../../assets/images/loterias/timemania.png'
import { useRouter } from 'next/router'
import { getLoteria } from '../../services/api-caixa'
import { useEffect, useState } from 'react'

export default function Loteria() {
  const router = useRouter();

  const { loteria } = router.query;
  const [result, setResult] = useState();
  useEffect(() => {
      console.log('lot', loteria)
      getLoteria(loteria as string)
        .then((data) => {
          setResult(data)
        })
        .catch(console.log)
  }, [loteria]) 
  

  let image;

  switch (loteria) {
    case 'lotomania':
      image = LotomaniaImage;
      break;
    case 'duplasena':
      image = DuplasenaImage;
      break;
    case 'lotofacil':
      image = LotofacilImage;
      break;
    case 'megasena':
      image = MegasenaImage;
      break;
    case 'quina':
      image = QuinaImage;
      break;
    case 'timenaia':
      image = TimemaniaImage;
      break;
    default:
      image = LotomaniaImage;
      break;
  }

  return (
    <>
      <Head>
        <title>{loteria}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        h="100vh"
        w="100vw"
        position="absolute"
      >
          <Box
            bgImage={image.src}
            h="100vh"
            bgSize="cover"
            bgPosition="center"
            position="relative"
          >
          </Box>
      </Box>
    </>
  )
}
