import Head from 'next/head'
import { Box } from '@chakra-ui/react'
import Monday from '../../assets/images/game-day/segunda.png'
import Tuesday from '../../assets/images/game-day/terca.png'
import Wednesday from '../../assets/images/game-day/quarta.png'
import Thursday from '../../assets/images/game-day/quinta.png'
import Friday from '../../assets/images/game-day/sexta.png'
import { StaticImageData } from 'next/image'
import { GetServerSideProps } from 'next'

type GameDayProps = {
  image: StaticImageData;
}

export default function GameDay({ image }: GameDayProps) {
  return (
    <>
      <Head>
        <title>Jogos do dia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        h="100vh"
        w="100vw"
        position="absolute"
      >
          <Box
            bgImage={image.src}
            h="100vh"
            bgSize="cover"
            bgPosition="center"
            position="relative"
          ></Box>
      </Box>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const image = getImage();   
  return {
    props: {
      image,
    }
  }
}

const getImage = (): StaticImageData => {
  const day = new Date().getDay();
  
  switch (day) {
  case 1:
    return Monday;
  case 2: 
    return Tuesday;
  case 3: 
    return Wednesday;
  case 4: 
    return Thursday;
  case 5: 
    return Friday;
  default:
    return Monday;
  }
}