/* eslint-disable no-restricted-syntax */
import Head from 'next/head';
import { GetStaticProps, NextPage } from 'next';
import { GameDay as GameDayComponent } from '../../components/GameDay';

import { EnumLoterias, getLoteria } from '../../services/api-caixa';
import { getLotoByDay } from '../../utils/getLotoByDay';

type GameDayProps = {
  color: string;
  data: {
    name: string;
    color: string;
    value: string;
  }[];
};

const GameDay: NextPage<GameDayProps> = ({ color, data }) => {
  return (
    <>
      <Head>
        <title>Jogos do dia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <GameDayComponent games={data} color={color} />
    </>
  );
};

export default GameDay;

export const getStaticProps: GetStaticProps = async () => {
  const lotoConfig = getLotoByDay();
  const configArray: Array<{
    name: string;
    color: string;
    value: string;
  }> = [];

  for (const gameDay of lotoConfig.data) {
    // eslint-disable-next-line no-await-in-loop
    const response = await getLoteria(
      gameDay.name as keyof typeof EnumLoterias
    );

    configArray.push({
      name: response.nome,
      color: gameDay.color,
      value: response.valor_acumulado.toLocaleString('pt-BR', {
        style: 'currency',
        currency: 'BRL'
      })
    });
  }

  return {
    props: {
      color: lotoConfig.color,
      data: configArray
    },
    revalidate: 60 * 60 * 16 // 16 hours
  };
};
