import Head from 'next/head'
import { Image, Box, Text } from '@chakra-ui/react'
import LotomaniaImage from '../assets/images/loterias/lotomania.png'

export default function Home() {
  return (
    <>
      <Head>
        <title>Loteria</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box>
          <Text>
            <Image
              src={LotomaniaImage.src}
              alt="Loteria"
              width="100vw"
              height="100vh"
              position="fixed"
              backgroundSize="cover"
            />
          </Text>
        </Box>
      </main>
    </>
  )
}
